# Generated by Django 4.2 on 2025-11-16 10:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/%Y/%m/%d/')),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('friends', 'Friends Only')], default='private', max_length=10)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Photo Category',
                'verbose_name_plural': 'Photo Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PhotoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Photo Tag',
                'verbose_name_plural': 'Photo Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='phototag',
            index=models.Index(fields=['name'], name='photos_phot_name_726af2_idx'),
        ),
        migrations.AddIndex(
            model_name='photocategory',
            index=models.Index(fields=['name'], name='photos_phot_name_fb2706_idx'),
        ),
        migrations.AddField(
            model_name='photo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='photos.photocategory'),
        ),
        migrations.AddField(
            model_name='photo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='photos', to='photos.phototag'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['owner', '-created_at'], name='photos_phot_owner_i_494f77_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['privacy', '-created_at'], name='photos_phot_privacy_044353_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['category'], name='photos_phot_categor_d05da2_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['-view_count'], name='photos_phot_view_co_41774f_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['-created_at'], name='photos_phot_created_d69ed2_idx'),
        ),
    ]
